import type { Scene, PaperPlaneFold, WeatherCondition, CompetitionRules } from '@/types';

export const SCENES: Scene[] = [
  {
    id: 'outdoor-grass',
    name: '户外草地',
    type: 'outdoor',
    skyTop: '#87CEEB',
    skyBottom: '#E0F4FF',
    groundColor: '#6BB35F',
    groundColor2: '#8CCB80',
    description: '晴朗的蓝天，柔软的草地，最适合纸飞机飞行的经典场景',
    baseWindSpeed: 1.2,
    turbulence: 0.2,
  },
  {
    id: 'indoor-room',
    name: '阳光房间',
    type: 'indoor',
    skyTop: '#FFF5E6',
    skyBottom: '#FFE8CC',
    groundColor: '#C49A6C',
    groundColor2: '#D9B38C',
    description: '温暖的室内，阳光从窗户洒入，在房间里自由飞翔',
    baseWindSpeed: 0,
    turbulence: 0,
    ceilingHeight: 6,
  },
  {
    id: 'classroom',
    name: '教室',
    type: 'indoor',
    skyTop: '#F5F0E6',
    skyBottom: '#E8E0D0',
    groundColor: '#A89078',
    groundColor2: '#BFA88C',
    description: '课间十分钟，在教室里来一场纸飞机大赛',
    baseWindSpeed: 0.2,
    turbulence: 0.05,
    ceilingHeight: 4.5,
  },
  {
    id: 'playground',
    name: '学校操场',
    type: 'outdoor',
    skyTop: '#82B8E8',
    skyBottom: '#C8E0F0',
    groundColor: '#D98050',
    groundColor2: '#E89870',
    description: '宽阔的塑胶跑道，是放飞纸飞机的理想场地',
    baseWindSpeed: 1.8,
    turbulence: 0.35,
  },
  {
    id: 'balcony',
    name: '高层阳台',
    type: 'balcony',
    skyTop: '#6BA8D9',
    skyBottom: '#A8C8E0',
    groundColor: '#5A8AA8',
    groundColor2: '#7A9FB8',
    description: '从高楼阳台起飞，俯瞰城市，享受长距离滑翔',
    baseWindSpeed: 3.5,
    turbulence: 0.5,
  },
  {
    id: 'canyon',
    name: '峡谷',
    type: 'canyon',
    skyTop: '#4A78A8',
    skyBottom: '#7A98B8',
    groundColor: '#8A6A50',
    groundColor2: '#A88A70',
    description: '崇山峻岭间的峡谷，气流复杂，极具挑战性',
    baseWindSpeed: 4.5,
    turbulence: 1.2,
  },
  {
    id: 'beach',
    name: '海边沙滩',
    type: 'outdoor',
    skyTop: '#5AB0E0',
    skyBottom: '#B0D8F0',
    groundColor: '#E8D090',
    groundColor2: '#F0DCAC',
    description: '海风吹拂，金色沙滩，让纸飞机与海浪齐飞',
    baseWindSpeed: 4.0,
    turbulence: 0.6,
  },
  {
    id: 'snowfield',
    name: '雪原',
    type: 'outdoor',
    skyTop: '#A8C0D8',
    skyBottom: '#D8E0E8',
    groundColor: '#F0F4F8',
    groundColor2: '#FFFFFF',
    description: '皑皑白雪，清冷空气，让纸飞机在冰原上轻盈起舞',
    baseWindSpeed: 2.5,
    turbulence: 0.4,
  },
];

const genPath = (type: string) => {
  const paths: Record<string, string> = {
    dart: 'M0,20 L80,18 L95,20 L80,22 L0,20 Z M80,18 L95,10 L95,20 Z M80,22 L95,30 L95,20 Z M40,20 L55,5 L65,20 Z M40,20 L55,35 L65,20 Z',
    glider: 'M10,20 L70,18 L90,20 L70,22 L10,20 Z M70,18 L90,6 L90,20 Z M70,22 L90,34 L90,20 Z M20,20 L50,0 L75,20 Z M20,20 L50,40 L75,20 Z',
    stunt: 'M5,20 L60,10 L80,20 L60,30 L5,20 Z M60,10 L95,5 L80,20 Z M60,30 L95,35 L80,20 Z M30,20 L55,2 L70,20 Z M30,20 L55,38 L70,20 Z',
    distance: 'M0,20 L75,17 L92,20 L75,23 L0,20 Z M75,17 L92,8 L92,20 Z M75,23 L92,32 L92,20 Z M35,20 L58,3 L72,20 Z M35,20 L58,37 L72,20 Z',
    acro: 'M15,20 L55,15 L75,20 L55,25 L15,20 Z M55,15 L95,8 L75,20 Z M55,25 L95,32 L75,20 Z M25,20 L50,5 L65,20 Z M25,20 L50,35 L65,20 Z',
    wide: 'M5,20 L65,18 L85,20 L65,22 L5,20 Z M65,18 L85,4 L85,20 Z M65,22 L85,36 L85,20 Z M15,20 L55,-2 L80,20 Z M15,20 L55,42 L80,20 Z',
    narrow: 'M0,20 L85,18 L98,20 L85,22 L0,20 Z M85,18 L98,12 L98,20 Z M85,22 L98,28 L98,20 Z M50,20 L65,10 L75,20 Z M50,20 L65,30 L75,20 Z',
  };
  return paths[type] || paths.dart;
};

export const FOLDS: PaperPlaneFold[] = [
  {
    id: 'dart',
    name: '经典飞镖',
    description: '流线型机身，速度快、距离远，是最经典的纸飞机折法',
    longDescription: '经典飞镖是纸飞机折法的入门之作，简单的6步折叠即可完成。它拥有出色的直线飞行能力，适合新手练习。投掷时建议以30-45度角向上抛出，可以获得最佳的飞行距离。',
    category: 'dart',
    difficulty: 1,
    bestScene: '学校操场',
    foldingSteps: 6,
    baseLiftCoeff: 0.42,
    baseDragCoeff: 0.028,
    baseStability: 0.85,
    maxSpeedFactor: 1.35,
    wingProfileId: 'flat',
    centerOfGravity: { x: 0.38, y: 0, massRatio: 1 },
    momentOfInertia: 0.08,
    svgPath: genPath('dart'),
    stats: { lift: 60, speed: 90, stability: 70, distance: 85, acrobatics: 40 },
  },
  {
    id: 'glider',
    name: '滑翔机',
    description: '宽大机翼带来出色升力，飞行平稳，滞空时间长',
    longDescription: '滑翔机拥有超宽的机翼和高升力翼型，能够在空中缓慢滑翔。它的飞行姿态优雅，适合在上升气流中长时间滞空。在有风的天气下表现更佳。',
    category: 'glider',
    difficulty: 2,
    bestScene: '峡谷',
    foldingSteps: 10,
    baseLiftCoeff: 0.72,
    baseDragCoeff: 0.055,
    baseStability: 1.15,
    maxSpeedFactor: 0.85,
    wingProfileId: 'highAspect',
    centerOfGravity: { x: 0.34, y: 0, massRatio: 1 },
    momentOfInertia: 0.12,
    svgPath: genPath('glider'),
    stats: { lift: 95, speed: 55, stability: 90, distance: 70, acrobatics: 30 },
  },
  {
    id: 'stunt',
    name: '特技旋风',
    description: '造型独特，能做出翻滚等特技动作，趣味性十足',
    longDescription: '特技旋风拥有独特的三角翼设计，配合后重心布局，使其具有极强的机动能力。能够完成滚转、俯冲等特技动作，是喜爱花式飞行玩家的最爱。',
    category: 'stunt',
    difficulty: 3,
    bestScene: '高层阳台',
    foldingSteps: 12,
    baseLiftCoeff: 0.50,
    baseDragCoeff: 0.045,
    baseStability: 0.55,
    maxSpeedFactor: 1.10,
    wingProfileId: 'delta',
    centerOfGravity: { x: 0.45, y: 0.02, massRatio: 1 },
    momentOfInertia: 0.05,
    svgPath: genPath('stunt'),
    stats: { lift: 70, speed: 75, stability: 40, distance: 60, acrobatics: 95 },
  },
  {
    id: 'distance',
    name: '世界纪录',
    description: '破纪录的优化设计，平衡升力与阻力，追求最远飞行距离',
    longDescription: '这款折法是纸飞机距离世界纪录的经典设计。经过空气动力学优化的翼型和机身，能够在保持高速的同时产生足够的升力。投掷时建议以20度角全力抛出。',
    category: 'distance',
    difficulty: 4,
    bestScene: '学校操场',
    foldingSteps: 16,
    baseLiftCoeff: 0.55,
    baseDragCoeff: 0.022,
    baseStability: 1.00,
    maxSpeedFactor: 1.20,
    wingProfileId: 'swept',
    centerOfGravity: { x: 0.36, y: 0, massRatio: 1 },
    momentOfInertia: 0.07,
    svgPath: genPath('distance'),
    stats: { lift: 75, speed: 85, stability: 80, distance: 95, acrobatics: 35 },
  },
  {
    id: 'acrobatic',
    name: '特技大师',
    description: '专为花式表演设计，能做出大回环、翻滚等高难度动作',
    longDescription: '特技大师是专为花式比赛设计的高性能折法。对称翼型配合中立重心，使其能够完成大回环、8字飞行等高级特技。对操控技巧要求较高，适合进阶玩家。',
    category: 'acrobatic',
    difficulty: 5,
    bestScene: '高层阳台',
    foldingSteps: 18,
    baseLiftCoeff: 0.55,
    baseDragCoeff: 0.05,
    baseStability: 0.4,
    maxSpeedFactor: 1.05,
    wingProfileId: 'symmetric',
    centerOfGravity: { x: 0.48, y: 0.05, massRatio: 1 },
    momentOfInertia: 0.04,
    svgPath: genPath('acro'),
    stats: { lift: 65, speed: 70, stability: 30, distance: 50, acrobatics: 98 },
  },
  {
    id: 'wide-wing',
    name: '宽翼大鹏',
    description: '超宽翼展，升力极强，适合长距离滑翔',
    category: 'glider',
    baseLiftCoeff: 0.82,
    baseDragCoeff: 0.06,
    baseStability: 1.1,
    maxSpeedFactor: 0.78,
    wingProfileId: 'highAspect',
    centerOfGravity: { x: 0.32, y: 0, massRatio: 1 },
    momentOfInertia: 0.14,
    svgPath: genPath('wide'),
    stats: { lift: 98, speed: 45, stability: 88, distance: 75, acrobatics: 25 },
  },
  {
    id: 'narrow-dart',
    name: '细身飞镖',
    description: '极窄机身，空气阻力最小，速度极快',
    category: 'dart',
    baseLiftCoeff: 0.35,
    baseDragCoeff: 0.018,
    baseStability: 0.75,
    maxSpeedFactor: 1.5,
    wingProfileId: 'swept',
    centerOfGravity: { x: 0.42, y: 0, massRatio: 1 },
    momentOfInertia: 0.06,
    svgPath: genPath('narrow'),
    stats: { lift: 45, speed: 98, stability: 65, distance: 80, acrobatics: 45 },
  },
  {
    id: 'camber-wing',
    name: '弯翼翱翔',
    description: '翼型带弧度，低速时升力优秀，适合滞空',
    category: 'glider',
    baseLiftCoeff: 0.78,
    baseDragCoeff: 0.048,
    baseStability: 1.05,
    maxSpeedFactor: 0.82,
    wingProfileId: 'cambered',
    centerOfGravity: { x: 0.35, y: -0.02, massRatio: 1 },
    momentOfInertia: 0.10,
    svgPath: genPath('glider'),
    stats: { lift: 92, speed: 58, stability: 85, distance: 72, acrobatics: 32 },
  },
  {
    id: 'delta-wing',
    name: '三角翼战机',
    description: '三角翼设计，失速抗性极强，适合大风天气',
    category: 'stunt',
    baseLiftCoeff: 0.52,
    baseDragCoeff: 0.05,
    baseStability: 0.7,
    maxSpeedFactor: 1.15,
    wingProfileId: 'delta',
    centerOfGravity: { x: 0.4, y: 0, massRatio: 1 },
    momentOfInertia: 0.07,
    svgPath: genPath('stunt'),
    stats: { lift: 68, speed: 80, stability: 65, distance: 68, acrobatics: 78 },
  },
  {
    id: 'stable-glide',
    name: '稳如磐石',
    description: '极高稳定性，即使新手也能飞得又稳又远',
    category: 'glider',
    baseLiftCoeff: 0.65,
    baseDragCoeff: 0.035,
    baseStability: 1.35,
    maxSpeedFactor: 0.9,
    wingProfileId: 'flat',
    centerOfGravity: { x: 0.3, y: -0.03, massRatio: 1 },
    momentOfInertia: 0.11,
    svgPath: genPath('dart'),
    stats: { lift: 78, speed: 65, stability: 98, distance: 78, acrobatics: 20 },
  },
  {
    id: 'speed-demon',
    name: '极速恶魔',
    description: '最高速度纪录保持者，一飞冲天瞬间消失',
    category: 'dart',
    baseLiftCoeff: 0.38,
    baseDragCoeff: 0.016,
    baseStability: 0.65,
    maxSpeedFactor: 1.6,
    wingProfileId: 'swept',
    centerOfGravity: { x: 0.45, y: 0, massRatio: 1 },
    momentOfInertia: 0.05,
    svgPath: genPath('narrow'),
    stats: { lift: 40, speed: 99, stability: 55, distance: 70, acrobatics: 50 },
  },
  {
    id: 'loop-master',
    name: '回环王者',
    description: '专业大回环机型，轻松完成360°甚至720°旋转',
    category: 'acrobatic',
    baseLiftCoeff: 0.58,
    baseDragCoeff: 0.042,
    baseStability: 0.35,
    maxSpeedFactor: 1.0,
    wingProfileId: 'symmetric',
    centerOfGravity: { x: 0.5, y: 0.08, massRatio: 1 },
    momentOfInertia: 0.035,
    svgPath: genPath('acro'),
    stats: { lift: 62, speed: 68, stability: 25, distance: 45, acrobatics: 99 },
  },
  {
    id: 'long-endurance',
    name: '滞空王者',
    description: '超长滞空时间设计，轻飘如羽',
    category: 'glider',
    baseLiftCoeff: 0.88,
    baseDragCoeff: 0.058,
    baseStability: 1.25,
    maxSpeedFactor: 0.7,
    wingProfileId: 'cambered',
    centerOfGravity: { x: 0.33, y: -0.04, massRatio: 0.9 },
    momentOfInertia: 0.13,
    svgPath: genPath('wide'),
    stats: { lift: 99, speed: 40, stability: 92, distance: 65, acrobatics: 18 },
  },
  {
    id: 'balance-pro',
    name: '全能平衡',
    description: '各项性能均衡，综合实力最强的万金油',
    category: 'distance',
    baseLiftCoeff: 0.6,
    baseDragCoeff: 0.03,
    baseStability: 1.0,
    maxSpeedFactor: 1.05,
    wingProfileId: 'flat',
    centerOfGravity: { x: 0.37, y: 0, massRatio: 1 },
    momentOfInertia: 0.085,
    svgPath: genPath('distance'),
    stats: { lift: 78, speed: 78, stability: 80, distance: 85, acrobatics: 55 },
  },
  {
    id: 'storm-rider',
    name: '风暴骑士',
    description: '大风天气专用，抗风能力出众',
    category: 'stunt',
    baseLiftCoeff: 0.48,
    baseDragCoeff: 0.038,
    baseStability: 0.9,
    maxSpeedFactor: 1.25,
    wingProfileId: 'delta',
    centerOfGravity: { x: 0.42, y: -0.01, massRatio: 1.1 },
    momentOfInertia: 0.09,
    svgPath: genPath('stunt'),
    stats: { lift: 60, speed: 85, stability: 82, distance: 72, acrobatics: 65 },
  },
  {
    id: 'precision',
    name: '精确打击',
    description: '飞行轨迹极直，适合精准投掷比赛',
    category: 'dart',
    baseLiftCoeff: 0.4,
    baseDragCoeff: 0.022,
    baseStability: 1.15,
    maxSpeedFactor: 1.3,
    wingProfileId: 'swept',
    centerOfGravity: { x: 0.4, y: -0.01, massRatio: 1 },
    momentOfInertia: 0.075,
    svgPath: genPath('dart'),
    stats: { lift: 52, speed: 88, stability: 92, distance: 82, acrobatics: 38 },
  },
  {
    id: 'butterfly',
    name: '蝶舞翩翩',
    description: '轻柔摆动的机翼，飞行如蝴蝶般优雅',
    category: 'glider',
    baseLiftCoeff: 0.7,
    baseDragCoeff: 0.052,
    baseStability: 0.8,
    maxSpeedFactor: 0.75,
    wingProfileId: 'cambered',
    centerOfGravity: { x: 0.36, y: 0.03, massRatio: 0.95 },
    momentOfInertia: 0.10,
    svgPath: genPath('wide'),
    stats: { lift: 88, speed: 48, stability: 68, distance: 60, acrobatics: 58 },
  },
  {
    id: 'fighter',
    name: '战斗机',
    description: '战斗机型设计，机动灵活，适合室内竞技',
    category: 'stunt',
    baseLiftCoeff: 0.5,
    baseDragCoeff: 0.04,
    baseStability: 0.6,
    maxSpeedFactor: 1.18,
    wingProfileId: 'delta',
    centerOfGravity: { x: 0.43, y: 0.02, massRatio: 1 },
    momentOfInertia: 0.055,
    svgPath: genPath('acro'),
    stats: { lift: 64, speed: 82, stability: 55, distance: 66, acrobatics: 85 },
  },
  {
    id: 'floater',
    name: '飘浮者',
    description: '极低翼载，下降速度极慢，享受缓缓飘落的乐趣',
    category: 'glider',
    baseLiftCoeff: 0.8,
    baseDragCoeff: 0.065,
    baseStability: 1.08,
    maxSpeedFactor: 0.65,
    wingProfileId: 'highAspect',
    centerOfGravity: { x: 0.31, y: -0.05, massRatio: 0.85 },
    momentOfInertia: 0.125,
    svgPath: genPath('wide'),
    stats: { lift: 96, speed: 38, stability: 86, distance: 55, acrobatics: 15 },
  },
  {
    id: 'daredevil',
    name: '亡命之徒',
    description: '极度不稳定，能做出最疯狂的特技动作',
    category: 'acrobatic',
    baseLiftCoeff: 0.45,
    baseDragCoeff: 0.055,
    baseStability: 0.25,
    maxSpeedFactor: 1.0,
    wingProfileId: 'symmetric',
    centerOfGravity: { x: 0.52, y: 0.1, massRatio: 1 },
    momentOfInertia: 0.03,
    svgPath: genPath('stunt'),
    stats: { lift: 50, speed: 72, stability: 15, distance: 40, acrobatics: 100 },
  },
  {
    id: 'champion',
    name: '冠军之翼',
    description: '多重世界冠军的御用折法，性能无与伦比',
    category: 'distance',
    baseLiftCoeff: 0.62,
    baseDragCoeff: 0.02,
    baseStability: 1.08,
    maxSpeedFactor: 1.28,
    wingProfileId: 'swept',
    centerOfGravity: { x: 0.37, y: -0.01, massRatio: 1 },
    momentOfInertia: 0.078,
    svgPath: genPath('distance'),
    stats: { lift: 82, speed: 92, stability: 88, distance: 98, acrobatics: 48 },
  },
  {
    id: 'sky-king',
    name: '天空之王',
    description: '传说中的顶级折法，集所有优点于一身',
    category: 'distance',
    baseLiftCoeff: 0.7,
    baseDragCoeff: 0.025,
    baseStability: 1.12,
    maxSpeedFactor: 1.18,
    wingProfileId: 'cambered',
    centerOfGravity: { x: 0.35, y: -0.02, massRatio: 0.98 },
    momentOfInertia: 0.09,
    svgPath: genPath('distance'),
    stats: { lift: 90, speed: 88, stability: 92, distance: 92, acrobatics: 60 },
  },
];

export const WEATHERS: WeatherCondition[] = [
  {
    id: 'sunny',
    name: '晴朗微风',
    windSpeed: 0.5,
    windDirection: 0,
    windGust: 0.8,
    humidity: 45,
    temperature: 22,
    turbulence: 0.1,
    precipitation: 'none',
    icon: '☀️',
  },
  {
    id: 'breeze',
    name: '和风习习',
    windSpeed: 2.0,
    windDirection: -10,
    windGust: 3.0,
    humidity: 55,
    temperature: 20,
    turbulence: 0.25,
    precipitation: 'none',
    icon: '🌬️',
  },
  {
    id: 'windy',
    name: '大风天气',
    windSpeed: 4.5,
    windDirection: -20,
    windGust: 7.0,
    humidity: 60,
    temperature: 16,
    turbulence: 0.6,
    precipitation: 'none',
    icon: '💨',
  },
  {
    id: 'gusty',
    name: '阵风乱流',
    windSpeed: 3.0,
    windDirection: 45,
    windGust: 8.0,
    humidity: 50,
    temperature: 18,
    turbulence: 1.0,
    precipitation: 'none',
    icon: '🌀',
  },
  {
    id: 'rainy',
    name: '小雨淅沥',
    windSpeed: 2.5,
    windDirection: 10,
    windGust: 4.0,
    humidity: 85,
    temperature: 14,
    turbulence: 0.4,
    precipitation: 'rain',
    icon: '🌧️',
  },
  {
    id: 'snowy',
    name: '雪花纷飞',
    windSpeed: 1.5,
    windDirection: -5,
    windGust: 2.5,
    humidity: 75,
    temperature: -2,
    turbulence: 0.3,
    precipitation: 'snow',
    icon: '❄️',
  },
  {
    id: 'calm',
    name: '无风室内',
    windSpeed: 0,
    windDirection: 0,
    windGust: 0,
    humidity: 40,
    temperature: 24,
    turbulence: 0,
    precipitation: 'none',
    icon: '🏠',
  },
  {
    id: 'hot-dry',
    name: '炎热干燥',
    windSpeed: 1.0,
    windDirection: 5,
    windGust: 1.5,
    humidity: 25,
    temperature: 35,
    turbulence: 0.45,
    precipitation: 'none',
    icon: '🔥',
  },
];

export const COMPETITION_MODES: CompetitionRules[] = [
  {
    mode: 'distance',
    rounds: 3,
    timeLimitSec: 0,
    minDistance: 5,
    scoring: { distanceWeight: 1.0, airTimeWeight: 0, acrobaticsWeight: 0 },
  },
  {
    mode: 'airtime',
    rounds: 3,
    timeLimitSec: 0,
    scoring: { distanceWeight: 0, airTimeWeight: 1.0, acrobaticsWeight: 0 },
  },
  {
    mode: 'acrobatic',
    rounds: 2,
    timeLimitSec: 30,
    scoring: { distanceWeight: 0, airTimeWeight: 0.3, acrobaticsWeight: 0.7 },
  },
  {
    mode: 'free',
    rounds: 1,
    timeLimitSec: 0,
    scoring: { distanceWeight: 0.5, airTimeWeight: 0.5, acrobaticsWeight: 0 },
  },
];

export const GLOBAL_LEADERBOARD_SEED = [
  { playerName: 'SkyMaster', country: '🇯🇵', foldName: '冠军之翼', totalScore: 982, grade: 'S' as const, distance: 68.5, airTime: 12.4, acrobaticsScore: 320 },
  { playerName: 'PaperAce', country: '🇺🇸', foldName: '世界纪录', totalScore: 958, grade: 'S' as const, distance: 72.1, airTime: 10.8, acrobaticsScore: 180 },
  { playerName: '纸飞机王', country: '🇨🇳', foldName: '天空之王', totalScore: 941, grade: 'S' as const, distance: 65.3, airTime: 11.9, acrobaticsScore: 250 },
  { playerName: 'GliderGuru', country: '🇩🇪', foldName: '滞空王者', totalScore: 912, grade: 'A' as const, distance: 42.0, airTime: 16.2, acrobaticsScore: 120 },
  { playerName: 'OrigamiFly', country: '🇫🇷', foldName: '滑翔机', totalScore: 887, grade: 'A' as const, distance: 55.8, airTime: 12.1, acrobaticsScore: 200 },
  { playerName: 'WindRider', country: '🇦🇺', foldName: '风暴骑士', totalScore: 863, grade: 'A' as const, distance: 60.2, airTime: 9.5, acrobaticsScore: 280 },
  { playerName: '飛行少年', country: '🇰🇷', foldName: '全能平衡', totalScore: 845, grade: 'A' as const, distance: 58.0, airTime: 10.6, acrobaticsScore: 220 },
  { playerName: 'StuntNinja', country: '🇯🇵', foldName: '回环王者', totalScore: 821, grade: 'B' as const, distance: 38.5, airTime: 8.2, acrobaticsScore: 450 },
  { playerName: 'PlaneCrafter', country: '🇨🇦', foldName: '精确打击', totalScore: 798, grade: 'B' as const, distance: 62.1, airTime: 6.8, acrobaticsScore: 90 },
  { playerName: '翱翔天际', country: '🇨🇳', foldName: '宽翼大鹏', totalScore: 775, grade: 'B' as const, distance: 45.3, airTime: 11.5, acrobaticsScore: 150 },
  { playerName: 'DartKing', country: '🇬🇧', foldName: '极速恶魔', totalScore: 752, grade: 'B' as const, distance: 58.8, airTime: 6.1, acrobaticsScore: 180 },
  { playerName: 'ButterflyBoy', country: '🇧🇷', foldName: '蝶舞翩翩', totalScore: 728, grade: 'B' as const, distance: 39.0, airTime: 10.2, acrobaticsScore: 320 },
  { playerName: 'AcroPro', country: '🇺🇸', foldName: '特技大师', totalScore: 710, grade: 'B' as const, distance: 32.5, airTime: 7.8, acrobaticsScore: 480 },
  { playerName: 'DistancePro', country: '🇩🇪', foldName: '世界纪录', totalScore: 695, grade: 'C' as const, distance: 65.2, airTime: 5.5, acrobaticsScore: 60 },
  { playerName: '飘雪的冬', country: '🇨🇳', foldName: '飘浮者', totalScore: 680, grade: 'C' as const, distance: 28.0, airTime: 15.8, acrobaticsScore: 80 },
];
